#!/bin/bash

echo ""
echo ""
echo -e "\033[36;1m Configuration de beef \033[0m"
echo ""
echo ""

echo ""
echo ""
echo -e "\033[36;1m Integration de metasploit... \033[0m"
echo ""
echo ""

echo ""
echo ""
echo -e "\033[36;1m
DANS LE FICHIER QUI VAS S'OUVRIR MODIFIER LA LIGNE 156 COMME CECI :

metasploit:
        enable: true
		        
VOUS POUVEZ MODIFIER VOTRE ID ET MDP BEEF A LA LIGNE 113 ET 114
\033[0m"
echo ""
echo ""

echo -e "\033[36;1m Appuyer sur <Entrée> pour continuer \033[0m"
read touche
case $touche in
					
	*)
		echo -e "\033[36;1m Demarrage de la configuration... \033[0m"
						;;
	esac
echo ""
echo ""
			
leafpad /etc/beef-xss/config.yaml
			
echo ""
echo ""
echo -e "\033[36;1m Configuration IP et auto msfrpcd... \033[0m"
echo ""
echo ""
			
sed -i 's/localhost/127.0.0.1/g' /usr/share/beef-xss/extensions/metasploit/config.yaml
sed -i 's/auto_msfrpcd: false/auto_msfrpcd: true/g' /usr/share/beef-xss/extensions/metasploit/config.yaml

echo ""
echo ""			
echo -e "\033[36;1m Mise en place de beef-strike... \033[0m"
echo ""
echo ""			

mv -f beef_strike/beef /usr/share/metasploit-framework/lib
mv -f beef_strike/beef.rb /usr/share/metasploit-framework/plugins

echo ""
echo ""
echo -e "\033[36;1m Installation des dependances via gem... \033[0m"
echo ""
echo ""
			
gem install hpricot json
cp -r /var/lib/gems/2.3.0/gems/hpricot-0.8.6/lib/* /usr/lib/ruby/vendor_ruby
rm -f /usr/bin/beef-xss

echo ""
echo ""			
echo -e "\033[36;1m Configuration de beef-strike... \033[0m"
echo ""
echo ""

echo -e "\033[36;1m
DANS LE FICHIER QUI VAS S'OUVRIR MODIFIER LE PORT A LA LIGNE 58 COMME CECI :

http://127.0.0.1:3000

VOUS POUVEZ MODIFIER VOTRE ID ET MDP BEEF A LA LIGNE 59 ET 60
\033[0m"
echo ""
echo ""

echo -e "\033[36;1m Appuyer sur <Entrée> pour continuer \033[0m"
read touche
case $touche in
			
	*)
		echo -e "\033[36;1m Reprise de l'installation... \033[0m"
		;;
	esac
echo ""
echo ""
			
leafpad /etc/beef-xss/config.yaml

echo ""
echo ""
echo -e "\033[36;1m Mise en place lancement beef via beef-xss... \033[0m"
echo ""
echo ""
			
echo "cd /usr/share/beef-xss" >> /usr/bin/beef-xss
echo "./beef" >> /usr/bin/beef-xss
chmod +x /usr/bin/beef-xss
			
echo ""
echo ""
echo -e "\033[36;1m Mise en place du fichier de redirectionnement dans /var/www/html... \033[0m"
echo ""
echo ""
			
mv -f beef_strike/index.html /var/www/html

echo ""
echo ""
echo -e "\033[36;1m Initialisation demarrage auto msfdb init... \033[0m"
echo ""
echo ""
			
msfdb init
			
echo ""
echo ""
echo -e "\033[36;1m
Ouvrez armitage
Rendez-vous dans Armitage/script/load/beef_strike
Selectionnez beef_strike.cna
Render-vous dans attacks/beef strike/start/connect
Renseignez les informations de connection comme ceci :
http://votre IP:3000
Votre ID (default = beef)
Votre MDP (default = beef)
Render-vous dans attacks/beef strike/start/key
Renseignez votre clef API (situer dans le panneau beef strike de armitage)
Render-vous dans attacks/beef strike/auto import/ON
A partir de maintenant chaque nouvelle victime online de beef apparaitra dans armitage
\033[0m"
echo ""
echo ""
